config/routes.rb
CbclInfo::Application.routes.draw do
  devise_for :users

  root :to => "home#index"
  match "/home/club" => "home#club"
  match "/home/party" => "home#party"
  match "/home/about" => "home#about"
  match "/home/contact" => "home#contact"
  resources :clubs do
    resources :members
    resources :parties
  end
  resources :parties
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/club.rb
class Club < ActiveRecord::Base
  attr_accessible :desc, :name, :url

  belongs_to :creator, :class_name => "User"
  has_many :join_clubs
  has_many :members, :through => :join_clubs
  has_many :parties

  validates :name, :presence => true
  validates :creator_id, :presence => true
  validates :url, :presence => true, :uniqueness => { :case_sensitive => false }
end

app/models/join_club.rb
class JoinClub < ActiveRecord::Base
  belongs_to :club, :counter_cache => true
  belongs_to :member, :class_name => "User", :counter_cache => true
  # attr_accessible :title, :body
end

app/models/party.rb
class Party < ActiveRecord::Base
  attr_accessible :date_at, :desc, :name
  belongs_to :club, :counter_cache => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
  attr_accessible :email, :password, :password_confirmation, :nickname

  has_many :join_clubs, :foreign_key => "member_id"
  has_many :clubs, :through => :join_clubs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clubs }
    end
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    @club = Club.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @club }
    end
  end

  # GET /clubs/new
  # GET /clubs/new.json
  def new
    @club = Club.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @club }
    end
  end

  # GET /clubs/1/edit
  def edit
    @club = Club.find(params[:id])
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(params[:club])
    @club.creator = current_user

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: '俱乐部创建成功，邀请你的朋友加入吧！' }
        format.json { render json: @club, status: :created, location: @club }
      else
        format.html { render action: "new" }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clubs/1
  # PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])

    respond_to do |format|
      if @club.update_attributes(params[:club])
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    @club.destroy

    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@pop_clubs = Club.order("join_clubs_count desc").limit(10)
  	@last_parties = Party.order("created_at desc").limit(10)
  	@act_clubs = Club.order("parties_count desc").limit(10)
  end

  def club
  	@clubs = Club.order("id asc").limit(50)
  end

  def party
  	@parties = Party.order("id desc").limit(50)
  end

  def about
  end

  def contact
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parties }
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @party = Party.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new
    @party = Party.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find(params[:id])
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(params[:party])

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    @party = Party.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/clubs/_form.html.erb
<%= simple_form_for @club, :validate => true do |f| %>
  <%= f.input :name %>
  <%= f.input :url %>
  <%= f.input :desc %>

  <%= f.button :submit %>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<h1>Listing clubs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clubs.each do |club| %>
  <tr>
    <td><%= link_to 'Show', club %></td>
    <td><%= link_to 'Edit', edit_club_path(club) %></td>
    <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Club', new_club_path %>

app/views/clubs/new.html.erb
<h1>创建新的俱乐部</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/home/about.html.erb
<% content_for :about do %>
class="active"
<% end %>
<div class="row">
  <h2>关于我们</h2>
  <p>
   	CBCL.info是一家免费为自行车运动俱乐部提供网络服务的供应商。在我们的平台上，会为每个加盟的俱乐部提供免费的主页，组织活动功能，以及俱乐部成员之间的消息广播功能。
  </p>
</div>

app/views/home/club.html.erb
<% content_for :club do %>
class="active"
<% end %>
<div class="row">
<h2>加盟俱乐部列表</h2>
  <ul>
  <% @clubs.each do |club|%>
    <li><%= club.name %>（ <%= club.join_clubs.size %>位会员）&nbsp; 组织 <%= club.parties.size %>次活动</li>
  <% end %>
  </ul>
</div>

app/views/home/contact.html.erb
<% content_for :contact do %>
class="active"
<% end %>
<div class="row">
  <h2>联系我们</h2>
  <p>
<a href="http://cbcl.info/">CBCL.info</a> <br />
给我发送电子邮件，与我联系，地址:<a href="mailto:my@cbcl.info">my@CBCL.info</a>
  </p>
</div>

app/views/home/index.html.erb
<% content_for :index do %>
class="active"
<% end %>
<div class="row">
  <div class="span7">
    <p class="muted lead">
      <strong>
      我们不是一个骑行俱乐部，<br /><br />
      我们为俱乐部提供召集活动工具，<br /><br />
      我们为俱乐部骑友提供一个交流的平台，<br /><br />
      我们是为骑友和俱乐部提供免费网络服务供应商
      </strong>
    </p>
  </div>
  
  <% if user_signed_in? %>
  <div class="span3 offset2">
    <%= link_to "创建俱乐部", new_club_path, :class => "btn btn-large btn-success" %>
  </div>
  <% else %>
  <div class="span5">
    <form class="form-horizontal" name="new_user_form" action="<%= registration_path("user")%>" method="post">
      <div class="control-group">
        <label class="control-label" for="inputEmail">电子邮件</label>
        <div class="controls">
          <input type="email" name="user[email]" id="inputEmail" placeholder="Email" />
        </div>
      </div>
      <div class="control-group">
        <label class="control-label"  for="inputNickname">昵称</label>
        <div class="controls">
          <input type="text"  name="user[nickname]" id="inputNickname" placeholder="昵称" />
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputPassword">输入密码</label>
        <div class="controls">
          <input type="password" name="user[password]" id="inputPassword" placeholder="密码" />
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputComfirmPassword">再次确认密码</label>
        <div class="controls">
          <input type="password" name="user[password_confirmation]" id="inputComfirmPassword" placeholder="再次确认密码" />
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" >&nbsp;</label>
        <div class="controls">
          <button type="submit" class="btn btn-large btn-success">立即加入我们</button>
        </div>
      </div>

    </form>
  </div>
  <% end %>
  
</div>
<hr />
      <div class="row">
        <div class="span4">
          <h3>最受欢迎俱乐部</h3>
          <ul>
            <% @pop_clubs.each do |club|%>
              <li> <%= club.name %>(<%= club.join_clubs.size%>位会员)&nbsp;<%= link_to "申请加入" %></li>
            <% end %>
          </ul>
        </div>
        
        <div class="span4">
          <h3>最活跃俱乐部</h3>
          <ul>
            <% @act_clubs.each do |club|%>
              <li> <%= club.name %>(组织<%= club.parties.size%>次活动)&nbsp;<%= link_to "申请加入" %></li>
            <% end %>
          </ul>
        </div>
       
        <div class="span4">
          <h3>最新活动</h3>
          <ul>
            <% @last_parties.each do |party|%>
              <li> 在<%= party.date_at %>，<%= party.club.name %>俱乐部组织“<%= party.name %>”活动&nbsp;<%= link_to "报名" %></li>
            <% end %>
          </ul>
        </div>
      </div>

app/views/home/party.html.erb
<% content_for :party do %>
class="active"
<% end %>
<div class="row">
<h2>组织活动列表</h2>
  <ul>
  <% @parties.each do |party|%>
    <li><%= party.club.name %>俱乐部在<%= party.date_at %>组织 <%= party.name %>活动</li>
  <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>单车运动俱乐部联盟 - CBCL.info</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if user_signed_in? %>
   您好， <%= current_user.nickname %> | <%= link_to "注销", destroy_user_session_path, method: :delete %>
<% else %>
   <%= link_to "登录", new_user_session_path %> | <%= link_to "加入我们",  new_user_registration_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>单车运动俱乐部联盟 - CBCL.info</title>
<meta name="keywords" content="单车 自行车 车队 骑行" />
<meta name="description" content="CBCL.info是一家免费为自行车运动俱乐部提供网络服务的供应商。在我们的平台上，会为每个加盟的俱乐部提供免费的主页，组织活动功能，以及俱乐部成员之间的消息广播功能。 " />
<meta name="author" content="CBCL.info" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">CBCL.info</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li <%= yield :index %>><%= link_to "首页", root_path %></li>
              <li <%= yield :club %>><%= link_to "俱乐部", home_club_path %></li>
              <li <%= yield :party %>><%= link_to "活动", home_party_path %></li>
              <li <%= yield :about %>><%= link_to "关于", home_about_path %></li>
              <li <%= yield :contact %>><%= link_to "联系", home_contact_path %></li>
            </ul>
              <% if user_signed_in? %>
                  <p class="pull-right">您好， <%= current_user.nickname %> | <%= link_to "注销", destroy_user_session_path, method: :delete %></p>
              <% else %>
                <form action="<%= session_path("user")%>" method="post" class="navbar-form pull-right">
                  <input class="span2" type="email" name="user[email]" placeholder="Email">
                  <input class="span2" type="password" name="user[password]" placeholder="密码">
                  <input name="user[remember_me]" type="hidden" value="1" /> 
                  <button type="submit" class="btn">登录</button>
                </form>
              <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <!-- Example row of columns -->
      <div>
        <%= image_tag "logo.png" %>
      </div>
      <%= yield%>

      <hr />

      <footer>
        <p>&copy;  2013 by <a href="http://www.huangxiaolei.com.cn">住在井底的青蛙</a>&nbsp;<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_5803173'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s13.cnzz.com/stat.php%3Fid%3D5803173' type='text/javascript'%3E%3C/script%3E"));</script></p>
      </footer>

    </div> <!-- /container -->
</body>
</html>

app/views/parties/_form.html.erb
<%= simple_form_for @party do |f| %>
  <%= f.input :name %>
  <%= f.input :date_at %>
  <%= f.input :desc %>

  <%= f.button :submit %>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<h1>Listing parties</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parties.each do |party| %>
  <tr>
    <td><%= link_to 'Show', party %></td>
    <td><%= link_to 'Edit', edit_party_path(party) %></td>
    <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>